### ISSUE TITLE
`client': uninitialized constant Azure::Resources (NameError) -- After recent changes

### ISSUE THREAD

**Issue by Tushard8** [chef/inspec-azure#58]
Hello Dear,

I was able to use the resource pack and could connect to azure vm's and tests there resources before recent updates & new commits.

However the moment I pulled the new code, my profile is failing with below errors. I have tried setting up credentials file at ~/.azure/credentials, also have tried adding required credentials as environment variables in my mac. Not sure what's going wrong it keep's throwing below error:
Is there a problem with recent check-ins ?

WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
libraries/azure_backend.rb:63:in `client': uninitialized constant Azure::Resources (NameError)
	from libraries/azure_backend.rb:201:in `initialize'
	from libraries/azure_generic_resource.rb:16:in `initialize'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/plugins/resource.rb:47:in `initialize'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/resource.rb:47:in `new'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/resource.rb:47:in `block (3 levels) in create_dsl'
	from inspec-azure-vm/controls/resources-check.rb:5:in `block in load_with_context'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/rule.rb:49:in `instance_eval'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/rule.rb:49:in `initialize'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/control_eval_context.rb:73:in `new'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/control_eval_context.rb:73:in `block (2 levels) in create'
	from inspec-azure-vm/controls/resources-check.rb:1:in `load_with_context'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/profile_context.rb:148:in `instance_eval'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/profile_context.rb:148:in `load_with_context'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/profile_context.rb:132:in `load_control_file'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/profile.rb:160:in `block in collect_tests'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/profile.rb:157:in `each'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/profile.rb:157:in `collect_tests'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/runner.rb:89:in `block in load'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/runner.rb:78:in `each'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/runner.rb:78:in `load'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/runner.rb:99:in `run'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/base_cli.rb:83:in `run_tests'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/lib/inspec/cli.rb:159:in `exec'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/gems/inspec-1.43.8/bin/inspec:12:in `<top (required)>'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/bin/inspec:23:in `load'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/bin/inspec:23:in `<main>'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tushard/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by Tushard8** [comment]
Appreciate your help at the earliest, I am kind of stuck here.

**Comment by russellseymour** [comment]
@Tushard8 Are you still having issues?
I really apologise for not getting back to you sooner.

**Comment by Tushard8** [comment]
@russellseymour no issues.

It's working fine now. Thanks for getting back !
